/**
 * Carried by every generated summary, inline and in the full-screen view.
 *
 * Not a nicety: the model reads a scanned report and can misread it, and the
 * doctor prescribes off what they see. It says so at the point of use rather
 * than once in a settings page nobody opens.
 *
 * Its own module because both summary cards show it, and one of them lives in
 * `pages/AppointmentPage.tsx` — importing it from there would have made the
 * page and the card import each other.
 */
export function AiDisclaimer() {
  return (
    <p className="ai-disclaimer">
      <InfoGlyph />
      <span>
        Generated by AI from the attached reports. It can be wrong or
        incomplete — read the reports yourself before prescribing. Not a
        diagnosis.
      </span>
    </p>
  );
}

function InfoGlyph() {
  return (
    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" aria-hidden>
      <circle cx="12" cy="12" r="9" stroke="currentColor" strokeWidth="1.8" />
      <path d="M12 11v5M12 8h.01" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" />
    </svg>
  );
}
