import { useEffect, useMemo, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { consultationApi, medicinesApi } from '../api/endpoints';
import type { EPrescription, PrescriptionMedicine } from '../api/types';
import { useToast } from './Toast';
import type { DraftFlushRef } from '../lib/draftFlush';
import { ConfirmDialog, Field } from './ui';
import { PrintPrescriptionButton } from './PrescriptionPreview';
import { ApiError } from '../api/client';
import { shareFile } from '../lib/shareFile';
import { formatDuration, parseDuration } from '../lib/duration';
import {
  buildMedicineIndex,
  checkMedicine,
  emptyIndex,
  suggestNames,
  type MedicineIndex,
} from '../lib/medicineCheck';
import {
  errorsFromApiDetails,
  hasErrors,
  noErrors,
  validatePrescription,
  type MedicineField,
  type PrescriptionErrors,
} from '../lib/prescriptionValidation';

/**
 * Sends the issued prescription out through the platform's share sheet as the
 * PDF itself — the doctor picks WhatsApp (or anything else the device offers)
 * and the patient receives the document, not a link that expires or needs a
 * login.
 *
 * The bytes come from the API rather than the presigned S3 URL next to this
 * button: that URL is fine for the browser to *navigate* to, but cannot be
 * read by script, because the bucket sends no CORS headers.
 */
function SharePrescriptionButton({ appointmentId }: { appointmentId: string }) {
  const toast = useToast();
  const [busy, setBusy] = useState(false);

  const onShare = async () => {
    setBusy(true);
    try {
      const { blob, filename } = await consultationApi.prescriptionPdf(appointmentId);
      const file = new File([blob], filename, { type: 'application/pdf' });
      const outcome = await shareFile(file, {
        title: 'Prescription',
        text: 'Prescription from your visit.',
      });
      if (outcome === 'downloaded') {
        toast.success(
          'Prescription downloaded',
          'This browser cannot open a share sheet — attach the saved PDF instead.',
        );
      }
    } catch (err) {
      toast.error(
        err instanceof ApiError ? err.message : 'Could not share the prescription.',
      );
    } finally {
      setBusy(false);
    }
  };

  return (
    <button className="btn btn-sm btn-primary" onClick={onShare} disabled={busy}>
      {busy ? 'Preparing…' : '↗ Share'}
    </button>
  );
}

/*
 * A doctor writes "Dolo 650mg", not a name in one box and a strength in
 * another. The stored shape keeps the two apart — the prescription PDF, the
 * medicine catalogue and the AI draft all read `strength` on its own — so the
 * single field is presentation only: joined for display, split again on every
 * keystroke.
 */

/** A trailing dose: a number and a unit, plus anything after it ("weekly"). */
const DOSE_SUFFIX = /\s+(\d+(?:\.\d+)?\s*(?:(?:mcg|mg|g|ml|iu|units?)\b|%).*)$/i;

function joinMedicine(name: string, strength?: string | null): string {
  return [name, strength].map((p) => (p ?? '').trim()).filter(Boolean).join(' ');
}

function splitMedicine(value: string): { medicine_name: string; strength: string } {
  const match = DOSE_SUFFIX.exec(value);
  // No recognisable dose yet — mid-typing "Dolo 65" is all name, and becomes
  // name + strength the moment the unit lands. What is displayed never changes
  // under the doctor either way, because display is the two joined back up.
  if (!match) return { medicine_name: value, strength: '' };
  return {
    medicine_name: value.slice(0, match.index).trim(),
    strength: match[1].trim(),
  };
}

/*
 * A row in the editor is a medicine plus a key of its own. The server's id
 * cannot be the React key: every save re-creates the medicine rows (new ids),
 * and with autosave that happens while the doctor is typing — a row keyed on
 * its id would be unmounted and remounted under their cursor, losing focus
 * and whatever the input held locally.
 */
type EditorRow = PrescriptionMedicine & { _key: string };

let keySeq = 0;
const newKey = () => `row-${++keySeq}`;

const blankRow = (): EditorRow => ({
  _key: newKey(),
  medicine_name: '',
  strength: '',
  dosage: '',
  duration_days: null,
  instructions: '',
  source: 'doctor',
});

const withKeys = (ms: PrescriptionMedicine[] | undefined): EditorRow[] =>
  ms && ms.length > 0 ? ms.map((m) => ({ ...m, _key: newKey() })) : [blankRow()];

/**
 * What the server holds, reduced to the parts the editor shows. Two states
 * with the same fingerprint are the same draft as far as the form is
 * concerned, even if the medicine ids underneath were regenerated by a save.
 */
const fingerprint = (p: EPrescription) =>
  JSON.stringify({
    d: p.diagnosis ?? '',
    a: p.advice ?? '',
    f: p.follow_up_date ?? '',
    m: (p.medicines ?? []).map((m) => [
      m.medicine_name,
      m.strength ?? '',
      m.form ?? '',
      m.dosage ?? '',
      m.duration_days ?? null,
      m.instructions ?? '',
    ]),
  });

/** How long the editor waits after the last keystroke before saving. */
const AUTOSAVE_DELAY_MS = 1500;

type SaveState = 'idle' | 'saving' | 'saved' | 'error';

/**
 * The doctor's review step. An AI draft lands here and nothing reaches the
 * patient until they press Issue — AI-suggested rows are marked so they get
 * looked at rather than skimmed.
 */
export function PrescriptionEditor({
  appointmentId,
  canEdit,
  flushRef,
}: {
  appointmentId: string;
  canEdit: boolean;
  /** Lets the Preview step save these fields before it renders. */
  flushRef?: DraftFlushRef;
}) {
  const qc = useQueryClient();
  const toast = useToast();

  /*
   * Loaded once for the editor rather than per row: it is the same list for
   * every medicine, it changes only when a prescription is issued, and the
   * check below has to compare against all of it rather than a search result.
   */
  const catalogQ = useQuery({
    queryKey: ['medicine-catalog'],
    queryFn: () => medicinesApi.catalog(),
    staleTime: 5 * 60 * 1000,
  });
  const medicineIndex: MedicineIndex = useMemo(
    () =>
      catalogQ.data ? buildMedicineIndex(catalogQ.data.map((m) => m.name)) : emptyIndex,
    [catalogQ.data],
  );

  const prescriptionQ = useQuery({
    queryKey: ['prescription', appointmentId],
    queryFn: () => consultationApi.prescription(appointmentId),
    // A background draft can land at any time while this is open.
    refetchInterval: (q) => (q.state.data?.status === 'draft' ? 5000 : false),
  });

  const [form, setForm] = useState({ diagnosis: '', advice: '', follow_up_date: '' });
  const [rows, setRows] = useState<EditorRow[]>([blankRow()]);
  const [dirty, setDirty] = useState(false);
  const [saveState, setSaveState] = useState<SaveState>('idle');
  const [errors, setErrors] = useState<PrescriptionErrors>(noErrors);
  const [confirmWithdraw, setConfirmWithdraw] = useState(false);
  const [confirmClear, setConfirmClear] = useState(false);
  const lastLoadedSessionRef = useRef<string | null>(null);

  /*
   * Autosave bookkeeping.
   *
   * `latest` is what the form holds right now, readable from a save that was
   * queued a render ago. `editVersion` goes up on every edit, so a save that
   * finishes can tell whether the doctor typed anything while it was in
   * flight — if they did, the form is still dirty and the next save will
   * carry it. `adopted` is the fingerprint of the server state the form was
   * last loaded from or saved to; a refetch that returns the same thing is
   * not a reason to touch the form.
   */
  const latestRef = useRef({ form, rows });
  latestRef.current = { form, rows };
  const dirtyRef = useRef(dirty);
  dirtyRef.current = dirty;
  const editVersionRef = useRef(0);
  const adoptedRef = useRef<string | null>(null);
  const saveChainRef = useRef<Promise<boolean> | null>(null);
  const autosaveTimerRef = useRef<number | null>(null);

  const markDirty = () => {
    editVersionRef.current += 1;
    setDirty(true);
  };

  const withdraw = useMutation({
    mutationFn: () => consultationApi.withdrawPrescription(appointmentId),
    onSuccess: () => {
      setConfirmWithdraw(false);
      // The editor reloads from the server as a draft; let the adopt effect
      // pick the medicines back up rather than second-guessing them here.
      lastLoadedSessionRef.current = null;
      setDirty(false);
      qc.invalidateQueries({ queryKey: ['prescription', appointmentId] });
      qc.invalidateQueries({ queryKey: ['appointment', appointmentId] });
      toast.success(
        'Prescription withdrawn',
        'It is a draft again and no longer visible to the patient. Correct it and issue again.',
      );
    },
    onError: (err: unknown) => {
      setConfirmWithdraw(false);
      toast.error(
        err instanceof ApiError ? err.message : 'Could not withdraw the prescription.',
      );
    },
  });

  /*
   * Adopt server state when it says something the form does not already.
   *
   * Runs on every refetch, and most refetches carry nothing new — the draft
   * the editor just autosaved, read back. Those are skipped by fingerprint,
   * which is what keeps a blank "+ Add medicine" row from vanishing under the
   * doctor every five seconds. A genuinely different draft is adopted when
   * the form has no unsaved edits, and always when it is a new AI draft.
   */
  useEffect(() => {
    const data = prescriptionQ.data;
    if (!data) return;

    const isNewAiDraft =
      !!data.consultation_session_id &&
      data.consultation_session_id !== lastLoadedSessionRef.current;
    const fp = fingerprint(data);

    if (fp === adoptedRef.current && !isNewAiDraft) return;
    if (dirtyRef.current && !isNewAiDraft) return;

    if (isNewAiDraft) lastLoadedSessionRef.current = data.consultation_session_id ?? null;
    adoptedRef.current = fp;
    setDirty(false);
    setForm({
      diagnosis: data.diagnosis ?? '',
      advice: data.advice ?? '',
      follow_up_date: data.follow_up_date ?? '',
    });
    setRows(withKeys(data.medicines));
  }, [prescriptionQ.data]);

  /**
   * Editor row indexes that end up in the payload, in payload order. Read
   * from `latestRef`, not the render's `rows`: a save can run from a closure
   * older than the form it is saving.
   */
  const sentRowIndexes = () =>
    latestRef.current.rows
      .map((r, i) => (r.medicine_name.trim() ? i : -1))
      .filter((i) => i >= 0);

  const body = () => {
    const { form: f, rows: rs } = latestRef.current;
    return {
      diagnosis: f.diagnosis || undefined,
      advice: f.advice || undefined,
      follow_up_date: f.follow_up_date || undefined,
      medicines: sentRowIndexes().map((i) => {
        const r = rs[i];
        return {
          id: r.id,
          medicine_name: r.medicine_name.trim(),
          strength: r.strength || undefined,
          form: r.form || undefined,
          dosage: r.dosage || undefined,
          duration_days: r.duration_days ?? undefined,
          instructions: r.instructions || undefined,
        };
      }),
    };
  };

  /**
   * Puts a failed submit where the doctor can act on it: the field that needs
   * attention gets the message inline, and the toast names it rather than
   * saying only that something went wrong.
   */
  const reportFailure = (e: unknown) => {
    if (e instanceof ApiError && e.statusCode === 422) {
      const mapped = errorsFromApiDetails(e.details, sentRowIndexes());
      if (hasErrors(mapped)) {
        setErrors(mapped);
        toast.error(new ApiError(e.code, mapped.summary ?? e.message, e.statusCode));
        return;
      }
    }
    toast.error(e);
  };

  /*
   * Nothing worth clearing? Then the button has nothing to do, and offering it
   * would be a control that answers "already done".
   */
  const isEmpty =
    !form.diagnosis.trim() &&
    !form.advice.trim() &&
    rows.every(
      (r) =>
        !r.medicine_name?.trim() &&
        !r.strength?.trim() &&
        !r.dosage?.trim() &&
        !r.instructions?.trim() &&
        r.duration_days == null,
    );

  /*
   * Back to a blank form, locally. The server still holds the last saved
   * version until Save draft is pressed — clearing is an edit like any other,
   * so a mis-click is undone by leaving the step rather than by a second
   * destructive call.
   */
  const clearAll = () => {
    markDirty();
    setForm({ diagnosis: '', advice: '', follow_up_date: form.follow_up_date });
    setRows([blankRow()]);
    setErrors(noErrors());
    setConfirmClear(false);
  };

  /**
   * Fold a saved draft back into the form without replacing it.
   *
   * Every save regenerates the medicine ids, and the next save needs them —
   * an AI-suggested row keeps its "AI suggested" mark only if it is sent back
   * under the id the server knows it by. So the ids are merged into the rows
   * that were sent, by position, and everything else the form holds (a blank
   * row the doctor just added, text typed since) is left exactly as it is.
   */
  const adoptSaved = (saved: EPrescription, versionAtStart: number) => {
    const sent = sentRowIndexes();
    const returned = saved.medicines ?? [];
    setRows((prev) =>
      prev.map((r, i) => {
        const at = sent.indexOf(i);
        const m = at >= 0 ? returned[at] : undefined;
        return m ? { ...r, id: m.id, source: m.source ?? r.source } : r;
      }),
    );
    adoptedRef.current = fingerprint(saved);
    qc.setQueryData(['prescription', appointmentId], saved);
    // Edits made while the request was in flight keep the form dirty; the
    // autosave that follows carries them.
    if (editVersionRef.current === versionAtStart) setDirty(false);
  };

  /** Returns true when the draft is clean; otherwise shows what is missing. */
  const check = (mode: 'save' | 'issue') => {
    const { form: f, rows: rs } = latestRef.current;
    const found = validatePrescription(f, rs, mode);
    setErrors(found);
    if (hasErrors(found)) {
      toast.error(new ApiError('VALIDATION_FAILED', found.summary!, 422));
      return false;
    }
    return true;
  };

  /**
   * One save, queued behind any save already running.
   *
   * Two saves in flight at once could land out of order — the server keeps
   * whichever arrives last — so they are chained. Each one reads the form as
   * it is when its turn comes, not as it was when it was queued.
   *
   *   auto    — silent: an invalid draft is simply not saved yet, and a failed
   *             request shows as "Couldn't save" beside the button.
   *   manual  — the Save draft button: errors and success both get a toast.
   *   flush   — on the way to Preview: errors are thrown for the page to show.
   */
  const saveNow = (how: 'auto' | 'manual' | 'flush'): Promise<boolean> => {
    const run = async (): Promise<boolean> => {
      if (!canEdit) return true;
      const version = editVersionRef.current;
      const { form: f, rows: rs } = latestRef.current;
      const found = validatePrescription(f, rs, 'save');
      if (hasErrors(found)) {
        if (how === 'auto') return false;
        setErrors(found);
        const err = new ApiError('VALIDATION_FAILED', found.summary!, 422);
        if (how === 'flush') throw err;
        toast.error(err);
        return false;
      }
      setSaveState('saving');
      try {
        const saved = await consultationApi.savePrescription(appointmentId, body());
        adoptSaved(saved, version);
        setErrors(noErrors());
        setSaveState('saved');
        if (how === 'manual') toast.success('Draft saved');
        return true;
      } catch (e) {
        setSaveState('error');
        if (how === 'flush') throw e;
        if (how === 'manual') reportFailure(e);
        return false;
      }
    };
    const prev = saveChainRef.current ?? Promise.resolve(false);
    const next = prev.then(run, run);
    saveChainRef.current = next;
    return next;
  };

  const cancelPendingAutosave = () => {
    if (autosaveTimerRef.current != null) {
      window.clearTimeout(autosaveTimerRef.current);
      autosaveTimerRef.current = null;
    }
  };

  /*
   * Save on its own, a moment after the doctor stops typing.
   *
   * The draft used to survive only if Save draft was pressed; a doctor who
   * typed three medicines, took a call and came back to the list found an
   * empty form. Every edit now restarts a short timer, and when it runs out
   * the draft goes to the server quietly — no toast, nothing moves.
   */
  useEffect(() => {
    if (!dirty || !canEdit) return;
    cancelPendingAutosave();
    autosaveTimerRef.current = window.setTimeout(() => {
      autosaveTimerRef.current = null;
      void saveNow('auto');
    }, AUTOSAVE_DELAY_MS);
    return cancelPendingAutosave;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dirty, form, rows, canEdit]);

  /*
   * The server renders from the stored draft, so the doctor's unsaved edits
   * have to reach it first — otherwise the Preview step would show the version
   * before the change they pressed the button to check.
   */
  const flush = async () => {
    cancelPendingAutosave();
    if (dirtyRef.current || saveChainRef.current) await saveNow('flush');
  };

  /*
   * The Preview step lives on the page now, not in this component, so it
   * cannot reach `flush` on its own. Re-registering after every commit keeps
   * the closure current — a dependency list would leave the step holding a
   * stale `body()` — while staying out of render, so a render React discards
   * cannot leave its closure behind.
   */
  useEffect(() => {
    if (flushRef) flushRef.current = flush;
  });

  const patchRow = (i: number, patch: Partial<PrescriptionMedicine>) => {
    markDirty();
    setRows((prev) => prev.map((r, idx) => (idx === i ? { ...r, ...patch } : r)));
    // Drop the message for a field the moment it's being fixed.
    setErrors((prev) => {
      const row = prev.rows[i];
      if (!row) return prev;
      const next = { ...row };
      for (const key of Object.keys(patch)) delete next[key as keyof typeof next];
      return { ...prev, rows: { ...prev.rows, [i]: next }, summary: undefined };
    });
  };

  const data = prescriptionQ.data;
  const issued = data?.status === 'issued';

  if (prescriptionQ.isLoading) {
    return <span className="muted">Loading prescription…</span>;
  }

  if (issued) {
    return (
      <div>
        <div className="row" style={{ justifyContent: 'space-between' }}>
          <span className="badge badge-available">Issued</span>
          <div className="row" style={{ gap: 8 }}>
            {data?.pdf_url && (
              <a className="btn btn-sm" href={data.pdf_url} target="_blank" rel="noreferrer">
                Download PDF
              </a>
            )}
            <PrintPrescriptionButton appointmentId={appointmentId} />
            <SharePrescriptionButton appointmentId={appointmentId} />
            {canEdit && (
              <button
                className="btn btn-sm"
                style={{ color: 'var(--state-error)' }}
                onClick={() => setConfirmWithdraw(true)}
                disabled={withdraw.isPending}
                title="Take this prescription back so it can be corrected"
              >
                {withdraw.isPending ? 'Withdrawing…' : 'Withdraw'}
              </button>
            )}
          </div>
        </div>
      {confirmWithdraw && (
          <ConfirmDialog
            title="Withdraw this prescription?"
            destructive
            busy={withdraw.isPending}
            confirmLabel="Withdraw"
            message={
              <>
                The patient can already see this prescription. Withdrawing it
                removes their copy and the PDF, and clears the notification they
                were sent.
                <br />
                <br />
                The medicines stay here as a draft so you can correct them and
                issue again.
              </>
            }
            onConfirm={() => withdraw.mutate()}
            onCancel={() => setConfirmWithdraw(false)}
          />
        )}

        {data?.diagnosis && (
          <p style={{ marginTop: 10 }}>
            <strong>Diagnosis:</strong> {data.diagnosis}
          </p>
        )}
        <ol style={{ margin: '10px 0 0 18px' }}>
          {data?.medicines.map((m) => (
            <li key={m.id} style={{ marginBottom: 4 }}>
              <strong>
                {m.medicine_name}
                {m.strength ? ` ${m.strength}` : ''}
              </strong>
              <span className="muted" style={{ fontSize: 13 }}>
                {' '}
                · {m.dosage}
                {m.instructions ? ` · ${m.instructions}` : ''}
                {m.duration_days ? ` · ${formatDuration(m.duration_days)}` : ''}
              </span>
            </li>
          ))}
        </ol>
        {data?.advice && (
          <p className="muted" style={{ marginTop: 10, whiteSpace: 'pre-wrap' }}>
            {data.advice}
          </p>
        )}
      </div>
    );
  }

  return (
    <div>
      {/*
        The design's three sections, each under its own heading rather than
        boxed in a labelled field: Diagnosis, Medicines, Advice. The follow-up
        date sits with the diagnosis because it is the other thing about the
        visit as a whole, not about one medicine.
      */}
      {/*
        Diagnosis, medicines, advice — the three the design asks for. The
        follow-up date used to sit beside the diagnosis; the client took it off
        the form. Whatever a prescription already holds is still loaded and
        saved back untouched, so removing the input loses no existing data.
      */}
      <div className="rx-section-title">Diagnosis</div>
      <Field label="" error={errors.header.diagnosis}>
        <input
          className="input"
          placeholder="e.g. Viral fever with mild myalgia"
          disabled={!canEdit}
          value={form.diagnosis}
          onChange={(e) => {
            markDirty();
            setForm({ ...form, diagnosis: e.target.value });
            setErrors((p) => ({ ...p, header: { ...p.header, diagnosis: undefined }, summary: undefined }));
          }}
        />
      </Field>

      <div className="rx-section-title">Medicines</div>
      {rows.length === 0 && (
        <span className="muted" style={{ fontSize: 13 }}>
          No medicines yet.
        </span>
      )}

      <div className="stack" style={{ gap: 8 }}>
        {rows.map((row, i) => (
          <MedicineRow
            key={row._key}
            index={i}
            total={rows.length}
            row={row}
            errors={errors.rows[i]}
            medicineIndex={medicineIndex}
            canEdit={canEdit}
            onChange={(patch) => patchRow(i, patch)}
            onRemove={() => {
              markDirty();
              setRows((prev) => {
                const next = prev.filter((_, idx) => idx !== i);
                return next.length > 0 ? next : [blankRow()];
              });
              // Row indexes shift, so old messages would point at the wrong row.
              setErrors(noErrors());
            }}
          />
        ))}
      </div>

      {canEdit && (
        <button
          className="add-med-btn"
          onClick={() => {
            markDirty();
            setRows((prev) => [...prev, blankRow()]);
          }}
        >
          + Add medicine
        </button>
      )}

      <div className="rx-section-title">Advice</div>
      <Field label="" error={errors.header.advice}>
        <textarea
          className="input"
          rows={3}
          placeholder="e.g. Plenty of fluids, rest, review after 3 days if symptoms persist"
          disabled={!canEdit}
          value={form.advice}
          onChange={(e) => {
            markDirty();
            setForm({ ...form, advice: e.target.value });
            setErrors((p) => ({ ...p, header: { ...p.header, advice: undefined }, summary: undefined }));
          }}
        />
      </Field>

      {canEdit && (
        <div className="row rx-actions" style={{ marginTop: 12 }}>
          {/*
            Starting over. A dictated draft that came out wrong is the common
            case — clearing three sections one field at a time is worse than
            re-dictating, which is what doctors were doing instead.
          */}
          <button
            className="btn btn-sm btn-ghost rx-clear"
            disabled={saveState === 'saving' || isEmpty}
            onClick={() => setConfirmClear(true)}
          >
            Clear all
          </button>
          {/*
            The draft saves itself; this says so. The button stays for the
            doctor who wants to see it happen, and as the retry when a save
            fails.
          */}
          <span
            className={`muted rx-save-state ${saveState === 'error' ? 'is-error' : ''}`}
            style={{ marginLeft: 'auto', fontSize: 12 }}
            aria-live="polite"
          >
            {saveState === 'saving'
              ? 'Saving…'
              : saveState === 'error'
                ? "Couldn't save"
                : dirty
                  ? 'Unsaved changes'
                  : saveState === 'saved'
                    ? 'Saved'
                    : ''}
          </span>
          <button
            className="btn btn-sm"
            disabled={saveState === 'saving' || !dirty}
            onClick={() => {
              cancelPendingAutosave();
              if (check('save')) void saveNow('manual');
            }}
          >
            {saveState === 'saving' ? 'Saving…' : 'Save draft'}
          </button>
          {/*
            Preview and Issue used to sit here. They belong to the page now:
            the consultation runs Reports → Prescription → Preview, and issuing
            is the last thing that happens on the last step. Two places to
            issue from meant a doctor could send a prescription to a patient
            without ever having looked at the page it renders as.

            The issue-level checks moved with it. They still run — the server
            refuses an unissuable draft with the same wording — so nothing is
            lost by not repeating them here.
          */}
        </div>
      )}

      {confirmClear && (
        <ConfirmDialog
          title="Clear this prescription?"
          message="The diagnosis, every medicine and the advice are emptied so you can start again. Nothing is sent to the patient, and the last saved version stays on the server until you save again."
          confirmLabel="Clear all"
          cancelLabel="Keep it"
          destructive
          onConfirm={clearAll}
          onCancel={() => setConfirmClear(false)}
        />
      )}
    </div>
  );
}

function MedicineRow({
  row,
  index,
  total,
  errors,
  medicineIndex,
  canEdit,
  onChange,
  onRemove,
}: {
  row: PrescriptionMedicine;
  index: number;
  total: number;
  errors?: Partial<Record<MedicineField, string>>;
  medicineIndex: MedicineIndex;
  canEdit: boolean;
  onChange: (patch: Partial<PrescriptionMedicine>) => void;
  onRemove: () => void;
}) {
  /*
   * Autocomplete comes from the catalogue the editor already holds, not from a
   * request per keystroke. The old version fired one search per row on mount
   * and another on every character typed, which on a four-medicine draft was
   * enough on its own to trip the API's rate limit.
   */
  const [query, setQuery] = useState(row.medicine_name ?? '');
  const suggestions = useMemo(
    () => (query.length >= 2 ? suggestNames(query, medicineIndex) : []),
    [query, medicineIndex],
  );

  const fromAi = row.source === 'ai';

  /*
   * Dictation does not fail by producing gibberish — it produces a real word
   * that sounds right ("Mounjaro" heard as "Munger"), which reads as perfectly
   * plausible in a list of medicines. So the name is checked against what this
   * clinic actually prescribes before it can be issued.
   *
   * A name the doctor typed themselves is only questioned when something in
   * the catalogue sounds exactly like it. Nagging them for prescribing
   * something new would be wrong — and would train them to ignore the warning
   * that matters.
   */
  const check = checkMedicine(row.medicine_name, medicineIndex);
  const showWarning = !check.known && (fromAi || check.suggestions.length > 0);

  // The design folds the per-medicine remark away behind a link; it opens on
  // its own when the row already carries one.
  const [remarkOpen, setRemarkOpen] = useState(!!row.instructions?.trim());

  /*
   * Duration is typed as words — "5 days", "2 weeks" — and stored as days.
   * The text is the row's own while it is being typed; it is only rewritten
   * from the number when the number changes underneath it (an AI draft
   * landing, Clear all), never as the parsed echo of what was just typed.
   */
  const [durationText, setDurationText] = useState(formatDuration(row.duration_days));
  useEffect(() => {
    const typed = parseDuration(durationText);
    const held = row.duration_days ?? null;
    if (Number.isNaN(typed) && Number.isNaN(held)) return;
    if (typed !== held) setDurationText(formatDuration(held));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [row.duration_days]);
  const durationUnreadable = !!durationText.trim() && Number.isNaN(parseDuration(durationText));

  return (
    <div className={`med-row ${fromAi ? 'from-ai' : ''}`}>
      {canEdit && (
        <button
          type="button"
          className="med-remove"
          onClick={onRemove}
          title={total > 1 ? 'Remove medicine' : 'Clear medicine'}
          aria-label={total > 1 ? 'Remove medicine' : 'Clear medicine'}
        >
          ×
        </button>
      )}

      {fromAi && <span className="med-ai-tag">AI suggested</span>}

      <div className="med-row-fields">
        <Field
          className="med-name"
          label="Medicine"
          error={errors?.medicine_name ?? errors?.strength}
        >
          <input
            className="input"
            list={`meds-${row.id ?? row.medicine_name}-${index}`}
            placeholder="e.g. Paracetamol 650mg"
            disabled={!canEdit}
            value={joinMedicine(row.medicine_name, row.strength)}
            onChange={(e) => {
              const parsed = splitMedicine(e.target.value);
              onChange(parsed);
              // Suggestions are matched on the name, so the dose must not be
              // part of the query.
              setQuery(parsed.medicine_name);
            }}
          />
          <datalist id={`meds-${row.id ?? row.medicine_name}-${index}`}>
            {suggestions.map((name) => (
              <option key={name} value={name} />
            ))}
          </datalist>
        </Field>

        <Field className="med-freq" label="Freq." error={errors?.dosage}>
          <input
            className="input"
            disabled={!canEdit}
            placeholder="1-0-1"
            value={row.dosage ?? ''}
            onChange={(e) => onChange({ dosage: e.target.value })}
          />
        </Field>

        <Field
          className="med-days"
          label="Duration"
          error={
            errors?.duration_days ??
            (durationUnreadable ? 'Try "5 days" or "2 weeks"' : undefined)
          }
        >
          <input
            className="input"
            type="text"
            autoComplete="off"
            placeholder="5 days"
            disabled={!canEdit}
            value={durationText}
            onChange={(e) => {
              setDurationText(e.target.value);
              // NaN marks text that is not a duration; validation refuses it.
              onChange({ duration_days: parseDuration(e.target.value) });
            }}
            onBlur={() => {
              // "2 wk" → "2 weeks", the way it will print.
              const n = parseDuration(durationText);
              if (n != null && !Number.isNaN(n)) setDurationText(formatDuration(n));
            }}
          />
        </Field>
      </div>

      {/*
        Dictation does not fail by producing gibberish — it produces a real
        word that sounds right ("Mounjaro" heard as "Munger"), which reads as
        perfectly plausible in a list of medicines. The warning sits under the
        row rather than inside the name field, where the design has no room.
      */}
      {showWarning && (
        <div className="med-warning">
          {check.suggestions.length > 0 ? (
            <>
              <span>Sounds like a medicine you prescribe — did you mean:</span>
              {check.suggestions.map((name) => (
                <button
                  key={name}
                  type="button"
                  className="med-suggest"
                  disabled={!canEdit}
                  onClick={() => {
                    onChange({ medicine_name: name });
                    setQuery(name);
                  }}
                >
                  {name}
                </button>
              ))}
            </>
          ) : (
            <span>Not in your medicine list — check the spelling before issuing.</span>
          )}
        </div>
      )}

      {remarkOpen ? (
        <div className="med-remark-field">
          <input
            className="input med-remark-input"
            placeholder="Remark for this medicine"
            disabled={!canEdit}
            autoFocus
            value={row.instructions ?? ''}
            onChange={(e) => onChange({ instructions: e.target.value })}
          />
          <button
            type="button"
            className="med-remark-toggle"
            onClick={() => {
              setRemarkOpen(false);
              onChange({ instructions: '' });
            }}
          >
            − Remove remark
          </button>
        </div>
      ) : (
        canEdit && (
          <button
            type="button"
            className="med-remark-toggle"
            onClick={() => setRemarkOpen(true)}
          >
            + Add remark
          </button>
        )
      )}
    </div>
  );
}
