import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { consultationApi, medicinesApi } from '../api/endpoints';
import type { EPrescription, PrescriptionMedicine } from '../api/types';
import { useToast } from './Toast';
import type { DraftFlushRef } from '../lib/draftFlush';
import { ConfirmDialog, Field } from './ui';
import { TrashIcon } from './icons';
import { PrintPrescriptionButton, WhatsAppPrescriptionButton } from './PrescriptionPreview';
import { ApiError } from '../api/client';
import { shareFile } from '../lib/shareFile';
import { formatDuration } from '../lib/duration';
import { MedicineHead, MedicineRow } from './MedicineRow';
import { TemplatePicker } from './TemplatePicker';
import { TemplateEditor } from './TemplateEditor';
import { templatesApi } from '../api/endpoints';
import type { PrescriptionTemplate } from '../api/types';
import { matchesExisting, worthSaving } from '../lib/templateSignature';
import { buildMedicineIndex, emptyIndex, type MedicineIndex } from '../lib/medicineCheck';
import {
  errorsFromApiDetails,
  hasErrors,
  noErrors,
  validatePrescription,
  type PrescriptionErrors,
} from '../lib/prescriptionValidation';

/**
 * Sends the issued prescription out through the platform's share sheet as the
 * PDF itself — the doctor picks WhatsApp (or anything else the device offers)
 * and the patient receives the document, not a link that expires or needs a
 * login.
 *
 * The bytes come from the API rather than the presigned S3 URL next to this
 * button: that URL is fine for the browser to *navigate* to, but cannot be
 * read by script, because the bucket sends no CORS headers.
 */
function SharePrescriptionButton({ appointmentId }: { appointmentId: string }) {
  const toast = useToast();
  const [busy, setBusy] = useState(false);

  const onShare = async () => {
    setBusy(true);
    try {
      const { blob, filename } = await consultationApi.prescriptionPdf(appointmentId);
      const file = new File([blob], filename, { type: 'application/pdf' });
      const outcome = await shareFile(file, {
        title: 'Prescription',
        text: 'Prescription from your visit.',
      });
      if (outcome === 'downloaded') {
        toast.success(
          'Prescription downloaded',
          'This browser cannot open a share sheet — attach the saved PDF instead.',
        );
      }
    } catch (err) {
      toast.error(
        err instanceof ApiError ? err.message : 'Could not share the prescription.',
      );
    } finally {
      setBusy(false);
    }
  };

  return (
    <button className="btn btn-sm btn-primary" onClick={onShare} disabled={busy}>
      {busy ? 'Preparing…' : '↗ Share'}
    </button>
  );
}

/*
 * See `lib/medicineName.ts` — shared with the template editor.
 */

/*
 * A row in the editor is a medicine plus a key of its own. The server's id
 * cannot be the React key: every save re-creates the medicine rows (new ids),
 * and with autosave that happens while the doctor is typing — a row keyed on
 * its id would be unmounted and remounted under their cursor, losing focus
 * and whatever the input held locally.
 */
type EditorRow = PrescriptionMedicine & { _key: string };

let keySeq = 0;
const newKey = () => `row-${++keySeq}`;

const blankRow = (): EditorRow => ({
  _key: newKey(),
  medicine_name: '',
  strength: '',
  dosage: '',
  duration_days: null,
  instructions: '',
  source: 'doctor',
});

const withKeys = (ms: PrescriptionMedicine[] | undefined): EditorRow[] =>
  ms && ms.length > 0 ? ms.map((m) => ({ ...m, _key: newKey() })) : [blankRow()];

/**
 * What the server holds, reduced to the parts the editor shows. Two states
 * with the same fingerprint are the same draft as far as the form is
 * concerned, even if the medicine ids underneath were regenerated by a save.
 */
const fingerprint = (p: EPrescription) =>
  JSON.stringify({
    d: p.diagnosis ?? '',
    h: p.previous_history ?? '',
    a: p.advice ?? '',
    f: p.follow_up_date ?? '',
    m: (p.medicines ?? []).map((m) => [
      m.medicine_name,
      m.strength ?? '',
      m.form ?? '',
      m.dosage ?? '',
      m.duration_days ?? null,
      m.instructions ?? '',
    ]),
  });

/** How long the editor waits after the last keystroke before saving. */
const AUTOSAVE_DELAY_MS = 1500;

type SaveState = 'idle' | 'saving' | 'saved' | 'error';

/**
 * The doctor's review step. An AI draft lands here and nothing reaches the
 * patient until they press Issue — AI-suggested rows are marked so they get
 * looked at rather than skimmed.
 */
export function PrescriptionEditor({
  appointmentId,
  canEdit,
  flushRef,
  showTemplates,
  footerExtras,
}: {
  appointmentId: string;
  canEdit: boolean;
  /** Lets the Preview step save these fields before it renders. */
  flushRef?: DraftFlushRef;
  /**
   * Offer templates. Type mode only: in Record mode the doctor is dictating,
   * and a menu that replaces what they just said is in the way rather than to
   * hand.
   */
  showTemplates?: boolean;
  /** The visit's own actions — Preview and Issue — placed in this footer. */
  footerExtras?: ReactNode;
}) {
  const qc = useQueryClient();
  const toast = useToast();

  /*
   * Loaded once for the editor rather than per row: it is the same list for
   * every medicine, it changes only when a prescription is issued, and the
   * check below has to compare against all of it rather than a search result.
   */
  const catalogQ = useQuery({
    queryKey: ['medicine-catalog'],
    queryFn: () => medicinesApi.catalog(),
    staleTime: 5 * 60 * 1000,
  });
  const medicineIndex: MedicineIndex = useMemo(
    () =>
      catalogQ.data ? buildMedicineIndex(catalogQ.data.map((m) => m.name)) : emptyIndex,
    [catalogQ.data],
  );

  const prescriptionQ = useQuery({
    queryKey: ['prescription', appointmentId],
    queryFn: () => consultationApi.prescription(appointmentId),
    // A background draft can land at any time while this is open.
    refetchInterval: (q) => (q.state.data?.status === 'draft' ? 5000 : false),
  });

  const [form, setForm] = useState({
    diagnosis: '',
    previous_history: '',
    advice: '',
    follow_up_date: '',
  });
  const [rows, setRows] = useState<EditorRow[]>([blankRow()]);
  /*
   * The history box is not part of the standard form. Most visits have no
   * history to record, and an empty box on every prescription is one more
   * thing to skip past. It opens when the dictation put something in it, or
   * when the doctor asks for it — and once open it stays open for the visit,
   * so clearing the text does not make the box vanish under their cursor.
   */
  const [historyOpen, setHistoryOpen] = useState(false);
  const [dirty, setDirty] = useState(false);
  const [saveState, setSaveState] = useState<SaveState>('idle');
  const [errors, setErrors] = useState<PrescriptionErrors>(noErrors);
  const [confirmWithdraw, setConfirmWithdraw] = useState(false);
  const [confirmClear, setConfirmClear] = useState(false);
  const lastLoadedSessionRef = useRef<string | null>(null);

  /*
   * Autosave bookkeeping.
   *
   * `latest` is what the form holds right now, readable from a save that was
   * queued a render ago. `editVersion` goes up on every edit, so a save that
   * finishes can tell whether the doctor typed anything while it was in
   * flight — if they did, the form is still dirty and the next save will
   * carry it. `adopted` is the fingerprint of the server state the form was
   * last loaded from or saved to; a refetch that returns the same thing is
   * not a reason to touch the form.
   */
  const latestRef = useRef({ form, rows });
  latestRef.current = { form, rows };
  const dirtyRef = useRef(dirty);
  dirtyRef.current = dirty;
  const editVersionRef = useRef(0);
  const adoptedRef = useRef<string | null>(null);
  const saveChainRef = useRef<Promise<boolean> | null>(null);
  const autosaveTimerRef = useRef<number | null>(null);

  const markDirty = () => {
    editVersionRef.current += 1;
    setDirty(true);
  };

  const withdraw = useMutation({
    mutationFn: () => consultationApi.withdrawPrescription(appointmentId),
    onSuccess: () => {
      setConfirmWithdraw(false);
      // The editor reloads from the server as a draft; let the adopt effect
      // pick the medicines back up rather than second-guessing them here.
      lastLoadedSessionRef.current = null;
      setDirty(false);
      qc.invalidateQueries({ queryKey: ['prescription', appointmentId] });
      qc.invalidateQueries({ queryKey: ['appointment', appointmentId] });
      toast.success(
        'Prescription withdrawn',
        'It is a draft again and no longer visible to the patient. Correct it and issue again.',
      );
    },
    onError: (err: unknown) => {
      setConfirmWithdraw(false);
      toast.error(
        err instanceof ApiError ? err.message : 'Could not withdraw the prescription.',
      );
    },
  });

  /*
   * Adopt server state when it says something the form does not already.
   *
   * Runs on every refetch, and most refetches carry nothing new — the draft
   * the editor just autosaved, read back. Those are skipped by fingerprint,
   * which is what keeps a blank "+ Add medicine" row from vanishing under the
   * doctor every five seconds. A genuinely different draft is adopted when
   * the form has no unsaved edits, and always when it is a new AI draft.
   */
  useEffect(() => {
    const data = prescriptionQ.data;
    if (!data) return;

    const isNewAiDraft =
      !!data.consultation_session_id &&
      data.consultation_session_id !== lastLoadedSessionRef.current;
    const fp = fingerprint(data);

    if (fp === adoptedRef.current && !isNewAiDraft) return;
    if (dirtyRef.current && !isNewAiDraft) return;

    if (isNewAiDraft) lastLoadedSessionRef.current = data.consultation_session_id ?? null;
    adoptedRef.current = fp;
    setDirty(false);
    setForm({
      diagnosis: data.diagnosis ?? '',
      previous_history: data.previous_history ?? '',
      advice: data.advice ?? '',
      follow_up_date: data.follow_up_date ?? '',
    });
    if (data.previous_history?.trim()) setHistoryOpen(true);
    setRows(withKeys(data.medicines));
  }, [prescriptionQ.data]);

  /**
   * Editor row indexes that end up in the payload, in payload order. Read
   * from `latestRef`, not the render's `rows`: a save can run from a closure
   * older than the form it is saving.
   */
  const sentRowIndexes = () =>
    latestRef.current.rows
      .map((r, i) => (r.medicine_name.trim() ? i : -1))
      .filter((i) => i >= 0);

  const body = () => {
    const { form: f, rows: rs } = latestRef.current;
    return {
      diagnosis: f.diagnosis || undefined,
      previous_history: f.previous_history || undefined,
      advice: f.advice || undefined,
      follow_up_date: f.follow_up_date || undefined,
      medicines: sentRowIndexes().map((i) => {
        const r = rs[i];
        return {
          id: r.id,
          medicine_name: r.medicine_name.trim(),
          strength: r.strength || undefined,
          form: r.form || undefined,
          dosage: r.dosage || undefined,
          duration_days: r.duration_days ?? undefined,
          instructions: r.instructions || undefined,
        };
      }),
    };
  };

  /**
   * Puts a failed submit where the doctor can act on it: the field that needs
   * attention gets the message inline, and the toast names it rather than
   * saying only that something went wrong.
   */
  const reportFailure = (e: unknown) => {
    if (e instanceof ApiError && e.statusCode === 422) {
      const mapped = errorsFromApiDetails(e.details, sentRowIndexes());
      if (hasErrors(mapped)) {
        setErrors(mapped);
        toast.error(new ApiError(e.code, mapped.summary ?? e.message, e.statusCode));
        return;
      }
    }
    toast.error(e);
  };

  /*
   * Nothing worth clearing? Then the button has nothing to do, and offering it
   * would be a control that answers "already done".
   */
  const isEmpty =
    !form.diagnosis.trim() &&
    !form.previous_history.trim() &&
    !form.advice.trim() &&
    rows.every(
      (r) =>
        !r.medicine_name?.trim() &&
        !r.strength?.trim() &&
        !r.dosage?.trim() &&
        !r.instructions?.trim() &&
        r.duration_days == null,
    );

  /*
   * Back to a blank form, locally. The server still holds the last saved
   * version until Save draft is pressed — clearing is an edit like any other,
   * so a mis-click is undone by leaving the step rather than by a second
   * destructive call.
   */
  const clearAll = () => {
    markDirty();
    setForm({
      diagnosis: '',
      previous_history: '',
      advice: '',
      follow_up_date: form.follow_up_date,
    });
    setHistoryOpen(false);
    setRows([blankRow()]);
    setErrors(noErrors());
    setConfirmClear(false);
  };

  /**
   * Fold a saved draft back into the form without replacing it.
   *
   * Every save regenerates the medicine ids, and the next save needs them —
   * an AI-suggested row keeps its "AI suggested" mark only if it is sent back
   * under the id the server knows it by. So the ids are merged into the rows
   * that were sent, by position, and everything else the form holds (a blank
   * row the doctor just added, text typed since) is left exactly as it is.
   */
  const adoptSaved = (saved: EPrescription, versionAtStart: number) => {
    const sent = sentRowIndexes();
    const returned = saved.medicines ?? [];
    setRows((prev) =>
      prev.map((r, i) => {
        const at = sent.indexOf(i);
        const m = at >= 0 ? returned[at] : undefined;
        return m ? { ...r, id: m.id, source: m.source ?? r.source } : r;
      }),
    );
    adoptedRef.current = fingerprint(saved);
    qc.setQueryData(['prescription', appointmentId], saved);
    // Edits made while the request was in flight keep the form dirty; the
    // autosave that follows carries them.
    if (editVersionRef.current === versionAtStart) setDirty(false);
  };

  /** Returns true when the draft is clean; otherwise shows what is missing. */
  const check = (mode: 'save' | 'issue') => {
    const { form: f, rows: rs } = latestRef.current;
    const found = validatePrescription(f, rs, mode);
    setErrors(found);
    if (hasErrors(found)) {
      toast.error(new ApiError('VALIDATION_FAILED', found.summary!, 422));
      return false;
    }
    return true;
  };

  /**
   * One save, queued behind any save already running.
   *
   * Two saves in flight at once could land out of order — the server keeps
   * whichever arrives last — so they are chained. Each one reads the form as
   * it is when its turn comes, not as it was when it was queued.
   *
   *   auto    — silent: an invalid draft is simply not saved yet, and a failed
   *             request shows as "Couldn't save" beside the button.
   *   manual  — the Save draft button: errors and success both get a toast.
   *   flush   — on the way to Preview: errors are thrown for the page to show.
   */
  const saveNow = (how: 'auto' | 'manual' | 'flush'): Promise<boolean> => {
    const run = async (): Promise<boolean> => {
      if (!canEdit) return true;
      const version = editVersionRef.current;
      const { form: f, rows: rs } = latestRef.current;
      const found = validatePrescription(f, rs, 'save');
      if (hasErrors(found)) {
        if (how === 'auto') return false;
        setErrors(found);
        const err = new ApiError('VALIDATION_FAILED', found.summary!, 422);
        if (how === 'flush') throw err;
        toast.error(err);
        return false;
      }
      setSaveState('saving');
      try {
        const saved = await consultationApi.savePrescription(appointmentId, body());
        adoptSaved(saved, version);
        setErrors(noErrors());
        setSaveState('saved');
        if (how === 'manual') toast.success('Draft saved');
        return true;
      } catch (e) {
        setSaveState('error');
        if (how === 'flush') throw e;
        if (how === 'manual') reportFailure(e);
        return false;
      }
    };
    const prev = saveChainRef.current ?? Promise.resolve(false);
    const next = prev.then(run, run);
    saveChainRef.current = next;
    return next;
  };

  const cancelPendingAutosave = () => {
    if (autosaveTimerRef.current != null) {
      window.clearTimeout(autosaveTimerRef.current);
      autosaveTimerRef.current = null;
    }
  };

  /*
   * Save on its own, a moment after the doctor stops typing.
   *
   * The draft used to survive only if Save draft was pressed; a doctor who
   * typed three medicines, took a call and came back to the list found an
   * empty form. Every edit now restarts a short timer, and when it runs out
   * the draft goes to the server quietly — no toast, nothing moves.
   */
  useEffect(() => {
    if (!dirty || !canEdit) return;
    cancelPendingAutosave();
    autosaveTimerRef.current = window.setTimeout(() => {
      autosaveTimerRef.current = null;
      void saveNow('auto');
    }, AUTOSAVE_DELAY_MS);
    return cancelPendingAutosave;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dirty, form, rows, canEdit]);

  /*
   * The server renders from the stored draft, so the doctor's unsaved edits
   * have to reach it first — otherwise the Preview step would show the version
   * before the change they pressed the button to check.
   */
  const flush = async () => {
    cancelPendingAutosave();
    if (dirtyRef.current || saveChainRef.current) await saveNow('flush');
  };

  /*
   * The Preview step lives on the page now, not in this component, so it
   * cannot reach `flush` on its own. Re-registering after every commit keeps
   * the closure current — a dependency list would leave the step holding a
   * stale `body()` — while staying out of render, so a render React discards
   * cannot leave its closure behind.
   */
  useEffect(() => {
    if (flushRef) flushRef.current = flush;
  });
  // On the way out: anything not yet autosaved goes now — a Clear all
  // followed by a quick tab switch must reach the server, or the next
  // recording adds to the draft that was cleared — and the hook is handed
  // back, so nothing flushes a form that is no longer on screen.
  useEffect(() => {
    return () => {
      cancelPendingAutosave();
      if (dirtyRef.current) void saveNow('auto');
      if (flushRef) flushRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const patchRow = (i: number, patch: Partial<PrescriptionMedicine>) => {
    markDirty();
    setRows((prev) => prev.map((r, idx) => (idx === i ? { ...r, ...patch } : r)));
    // Drop the message for a field the moment it's being fixed.
    setErrors((prev) => {
      const row = prev.rows[i];
      if (!row) return prev;
      const next = { ...row };
      for (const key of Object.keys(patch)) delete next[key as keyof typeof next];
      return { ...prev, rows: { ...prev.rows, [i]: next }, summary: undefined };
    });
  };

  const data = prescriptionQ.data;
  /* ── Templates ──────────────────────────────────────────────
     Applying replaces the draft server-side and hands back the prescription
     in the shape this query already holds, so the result is adopted directly
     instead of being refetched — a refetch would race the autosave and could
     land the old draft back on top of the template. */
  const [pendingTemplate, setPendingTemplate] = useState<PrescriptionTemplate | null>(null);
  const [applied, setApplied] = useState<string | null>(null);
  const [saveAsTemplate, setSaveAsTemplate] = useState(false);

  const templatesQ = useQuery({
    queryKey: ['templates'],
    queryFn: () => templatesApi.list(),
    staleTime: 60 * 1000,
    enabled: !!showTemplates,
  });
  const categoriesQ = useQuery({
    queryKey: ['template-categories'],
    queryFn: () => templatesApi.categories(),
    staleTime: 60 * 1000,
    enabled: !!showTemplates,
  });

  const applyTemplate = useMutation({
    mutationFn: (t: PrescriptionTemplate) => {
      // Nothing half-typed should be saved on top of what is about to replace
      // it, and the server write must not race a queued autosave.
      cancelPendingAutosave();
      return templatesApi.apply(t.id, appointmentId);
    },
    onSuccess: (next, t) => {
      qc.setQueryData(['prescription', appointmentId], next);
      adoptedRef.current = fingerprint(next);
      setDirty(false);
      setErrors(noErrors());
      setForm({
        diagnosis: next.diagnosis ?? '',
        previous_history: next.previous_history ?? '',
        advice: next.advice ?? '',
        follow_up_date: next.follow_up_date ?? '',
      });
      if (next.previous_history?.trim()) setHistoryOpen(true);
      setRows(withKeys(next.medicines));
      setApplied(t.name);
      setPendingTemplate(null);
      qc.invalidateQueries({ queryKey: ['templates'] });
    },
    onError: (e) => {
      setPendingTemplate(null);
      toast.error(e instanceof ApiError ? e : 'Could not apply the template.');
    },
  });

  /**
   * Picking a template when the draft already has medicines asks first. The
   * prototype has no guard here; on a phone an accidental tap on a menu row
   * would wipe a prescription that had just been written.
   */
  const pickTemplate = (t: PrescriptionTemplate) => {
    const written = latestRef.current.rows.some((r) => r.medicine_name.trim());
    if (written) setPendingTemplate(t);
    else applyTemplate.mutate(t);
  };

  /** Something here, and nothing saved that already says it. */
  const canSaveAsTemplate =
    !!showTemplates &&
    worthSaving(rows, form.advice) &&
    !matchesExisting(rows, form.advice, templatesQ.data ?? []);

  const issued = data?.status === 'issued';

  if (prescriptionQ.isLoading) {
    return <span className="muted">Loading prescription…</span>;
  }

  if (issued) {
    return (
      <div>
        <div className="row" style={{ justifyContent: 'space-between' }}>
          <span className="badge badge-available">Issued</span>
          <div className="row" style={{ gap: 8 }}>
            {data?.pdf_url && (
              <a className="btn btn-sm" href={data.pdf_url} target="_blank" rel="noreferrer">
                Download PDF
              </a>
            )}
            <PrintPrescriptionButton appointmentId={appointmentId} />
            <SharePrescriptionButton appointmentId={appointmentId} />
            <WhatsAppPrescriptionButton appointmentId={appointmentId} />
            {canEdit && (
              <button
                className="btn btn-sm"
                style={{ color: 'var(--state-error)' }}
                onClick={() => setConfirmWithdraw(true)}
                disabled={withdraw.isPending}
                title="Take this prescription back so it can be corrected"
              >
                {withdraw.isPending ? 'Withdrawing…' : 'Withdraw'}
              </button>
            )}
          </div>
        </div>
      {confirmWithdraw && (
          <ConfirmDialog
            title="Withdraw this prescription?"
            destructive
            busy={withdraw.isPending}
            confirmLabel="Withdraw"
            message={
              <>
                The patient can already see this prescription. Withdrawing it
                removes their copy and the PDF, and clears the notification they
                were sent.
                <br />
                <br />
                The medicines stay here as a draft so you can correct them and
                issue again.
              </>
            }
            onConfirm={() => withdraw.mutate()}
            onCancel={() => setConfirmWithdraw(false)}
          />
        )}

        {data?.previous_history && (
          <p style={{ marginTop: 10 }}>
            <strong>Previous history:</strong> {data.previous_history}
          </p>
        )}
        {data?.diagnosis && (
          <p style={{ marginTop: data?.previous_history ? 6 : 10 }}>
            <strong>Diagnosis:</strong> {data.diagnosis}
          </p>
        )}
        <ol style={{ margin: '10px 0 0 18px' }}>
          {data?.medicines.map((m) => (
            <li key={m.id} style={{ marginBottom: 4 }}>
              <strong>
                {m.medicine_name}
                {m.strength ? ` ${m.strength}` : ''}
              </strong>
              <span className="muted" style={{ fontSize: 13 }}>
                {' '}
                · {m.dosage}
                {m.instructions ? ` · ${m.instructions}` : ''}
                {m.duration_days ? ` · ${formatDuration(m.duration_days)}` : ''}
              </span>
            </li>
          ))}
        </ol>
        {data?.advice && (
          <p className="muted" style={{ marginTop: 10, whiteSpace: 'pre-wrap' }}>
            {data.advice}
          </p>
        )}
      </div>
    );
  }

  return (
    <div>
      {/*
        The design's three sections, each under its own heading rather than
        boxed in a labelled field: Diagnosis, Medicines, Advice. The follow-up
        date sits with the diagnosis because it is the other thing about the
        visit as a whole, not about one medicine.
      */}
      {/*
        Diagnosis, medicines, advice — the three the design asks for. The
        follow-up date used to sit beside the diagnosis; the client took it off
        the form. Whatever a prescription already holds is still loaded and
        saved back untouched, so removing the input loses no existing data.
      */}
      {/*
        Previous history — only when there is some. The recorder fills it when
        the doctor dictates the patient's background ("known diabetic",
        "allergic to penicillin"); otherwise it is one link, not a box.

        It opens the prescription, above the diagnosis: the background is what
        the diagnosis is read against, on this form and on the printed sheet,
        which orders the two the same way.
      */}
      {historyOpen ? (
        <>
          <div className="rx-section-title row" style={{ justifyContent: 'space-between' }}>
            <span>Previous history</span>
            {/* Removes the line from the prescription, not just from view:
                the text is cleared and the box closes, and the next save
                sends it empty. Add it back with the link if that was a slip.
                A bin rather than the word "Remove", which read as a heading of
                its own beside the section title. */}
            {canEdit && (
              <button
                type="button"
                className="rx-history-remove"
                title="Remove previous history"
                aria-label="Remove previous history"
                onClick={() => {
                  markDirty();
                  setForm({ ...form, previous_history: '' });
                  setHistoryOpen(false);
                }}
              >
                <TrashIcon size={14} />
              </button>
            )}
          </div>
          <Field label="">
            <textarea
              className="input"
              rows={2}
              placeholder="e.g. Known diabetic for 10 years; allergic to penicillin"
              disabled={!canEdit}
              value={form.previous_history}
              onChange={(e) => {
                markDirty();
                setForm({ ...form, previous_history: e.target.value });
              }}
            />
          </Field>
        </>
      ) : (
        canEdit && (
          <button
            type="button"
            className="link-btn"
            onClick={() => setHistoryOpen(true)}
          >
            + Add previous history
          </button>
        )
      )}

      {showTemplates && canEdit && (
        <div className="rx-tpl-bar">
          <TemplatePicker disabled={applyTemplate.isPending} onPick={pickTemplate} />
          {/*
            Inline rather than a toast: the thing to check is the frequency of
            each medicine, and that is on this screen. A toast that says so and
            then disappears asks the doctor to remember it instead.
          */}
          {applied && (
            <span className="rx-tpl-applied" role="status">
              <b>{applied}</b> applied — check the frequency of each medicine
            </span>
          )}
        </div>
      )}

      <div className="rx-section-title">Diagnosis</div>
      <Field label="" error={errors.header.diagnosis}>
        <input
          className="input"
          placeholder="e.g. Viral fever with mild myalgia"
          disabled={!canEdit}
          value={form.diagnosis}
          onChange={(e) => {
            markDirty();
            setForm({ ...form, diagnosis: e.target.value });
            setErrors((p) => ({ ...p, header: { ...p.header, diagnosis: undefined }, summary: undefined }));
          }}
        />
      </Field>

      {/* The design puts Add medicine on the heading line, not under the
          rows: it is the section's own action, and at the bottom it moved
          down the page as the list grew. */}
      <div className="rx-lbl-row">
        <span className="rx-section-title">Medicines</span>
        {canEdit && (
          <button
            className="btn btn-sm btn-primary"
            onClick={() => {
              markDirty();
              setRows((prev) => [...prev, blankRow()]);
            }}
          >
            + Add medicine
          </button>
        )}
      </div>

      {rows.length > 0 && <MedicineHead />}
      {rows.length === 0 && (
        <span className="muted" style={{ fontSize: 13 }}>
          No medicines yet.
        </span>
      )}

      {rows.map((row, i) => (
        <MedicineRow
          key={row._key}
          listId={`meds-${row._key}`}
          row={row}
          errors={errors.rows[i]}
          medicineIndex={medicineIndex}
          canEdit={canEdit}
          onChange={(patch) => patchRow(i, patch)}
          onRemove={() => {
            markDirty();
            setRows((prev) => {
              const next = prev.filter((_, idx) => idx !== i);
              return next.length > 0 ? next : [blankRow()];
            });
            // Row indexes shift, so old messages would point at the wrong row.
            setErrors(noErrors());
          }}
        />
      ))}

      <div className="rx-section-title">Advice</div>
      <Field label="" error={errors.header.advice}>
        <textarea
          className="input"
          rows={3}
          placeholder="e.g. Plenty of fluids, rest, review after 3 days if symptoms persist"
          disabled={!canEdit}
          value={form.advice}
          onChange={(e) => {
            markDirty();
            setForm({ ...form, advice: e.target.value });
            setErrors((p) => ({ ...p, header: { ...p.header, advice: undefined }, summary: undefined }));
          }}
        />
      </Field>

      {canEdit && (
        /*
          One row, as the design has it: Clear · Save as template · Draft
          saved ···· Preview · Issue. Preview and Issue are the page's, handed
          down as `footerExtras` — they act on the visit rather than on this
          form, and the same two have to appear under the handwriting pad and
          the upload pane, where this editor does not render.
        */
        <div className="vfoot">
          {/*
            Starting over. A dictated draft that came out wrong is the common
            case — clearing three sections one field at a time is worse than
            re-dictating, which is what doctors were doing instead.
          */}
          <button
            className="btn btn-sm btn-ghost rx-clear"
            disabled={saveState === 'saving' || isEmpty}
            onClick={() => setConfirmClear(true)}
          >
            Clear all
          </button>
          {/*
            Offered only when this prescription says something no template
            already says. Signing on medicines *and* advice matters: the
            prototype signs on medicine names alone, so every advice-only
            prescription signs identically to every other and the button
            vanishes on exactly the ones this feature was asked for.
          */}
          {showTemplates && canSaveAsTemplate && (
            <button
              className="btn btn-sm btn-ghost"
              onClick={() => setSaveAsTemplate(true)}
            >
              Save as template
            </button>
          )}
          {/*
            The draft saves itself; this says so. The button stays for the
            doctor who wants to see it happen, and as the retry when a save
            fails.
          */}
          <span
            className={`muted rx-save-state ${saveState === 'error' ? 'is-error' : ''}`}
            aria-live="polite"
          >
            {saveState === 'saving'
              ? 'Saving…'
              : saveState === 'error'
                ? "Couldn't save"
                : dirty
                  ? 'Unsaved changes'
                  : saveState === 'saved'
                    ? 'Saved'
                    : ''}
          </span>
          {/* Only when there is something to retry. The draft saves itself,
              and a permanently-present Save button beside five other controls
              was the widest thing in a row the design keeps to one line. */}
          {(dirty || saveState === 'error') && (
            <button
              className="btn btn-sm rx-save-now"
              disabled={saveState === 'saving'}
              onClick={() => {
                cancelPendingAutosave();
                if (check('save')) void saveNow('manual');
              }}
            >
              {saveState === 'saving' ? 'Saving…' : 'Save now'}
            </button>
          )}
          <div className="vfoot-grow" />
          {footerExtras}
        </div>
      )}

      {confirmClear && (
        <ConfirmDialog
          title="Clear this prescription?"
          message="The diagnosis, every medicine and the advice are emptied so you can start again. Nothing is sent to the patient, and the last saved version stays on the server until you save again."
          confirmLabel="Clear all"
          cancelLabel="Keep it"
          destructive
          onConfirm={clearAll}
          onCancel={() => setConfirmClear(false)}
        />
      )}

      {/* The overwrite guard the prototype does not have. */}
      {pendingTemplate && (
        <ConfirmDialog
          title="Replace this prescription?"
          message={
            <>
              <b>{pendingTemplate.name}</b> replaces the medicines and advice
              already written here. The diagnosis you typed is kept.
            </>
          }
          confirmLabel="Apply template"
          cancelLabel="Keep what I wrote"
          busy={applyTemplate.isPending}
          onConfirm={() => applyTemplate.mutate(pendingTemplate)}
          onCancel={() => setPendingTemplate(null)}
        />
      )}

      {saveAsTemplate && (
        <TemplateEditor
          template={null}
          categories={categoriesQ.data ?? []}
          prefill={{
            // The diagnosis is the doctor's own words for what this treats,
            // which is the name they would have typed anyway.
            name: form.diagnosis.trim() || undefined,
            advice: form.advice.trim() || undefined,
            medicines: rows
              .filter((r) => r.medicine_name.trim())
              .map((r) => ({
                medicine_name: r.medicine_name.trim(),
                strength: r.strength ?? undefined,
                form: r.form ?? undefined,
                dosage: r.dosage ?? '',
                duration_days: r.duration_days ?? undefined,
                instructions: r.instructions ?? undefined,
              })),
          }}
          onClose={() => setSaveAsTemplate(false)}
        />
      )}
    </div>
  );
}

